package com.stb.minipos.ui.base;

import android.os.Bundle;
import android.support.v4.app.DialogFragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

public abstract class UIDialogFragment extends DialogFragment implements
		IDrawerFragment {

	@Override
	public View onCreateView(LayoutInflater inflater, ViewGroup container,
			Bundle savedInstanceState) {
		return getContentView(inflater, container, savedInstanceState);
	}

	public void switchState(UIDialogFragment state, int flags) {
		if (getActivity() instanceof UIDrawerActivity) {
			((UIDrawerActivity) getActivity()).switchState(state, flags);
		}
	}

	public void switchState(UIDialogFragment state) {
		if (getActivity() instanceof UIDrawerActivity) {
			((UIDrawerActivity) getActivity()).switchState(state);
		}
	}

	@Override
	public void onDrawerVisible() {

	}

	@Override
	public void onDrawerClosed(View drawerView) {

	}

	@Override
	public void onDrawerOpened(View drawerView) {

	}

	public boolean onBackPress() {
		return false;
	}

	/**
	 * get the XML layout id for the fragment
	 * 
	 * @return id of the XML layout is generated by Android
	 */
	public abstract int getContentResource();

	/**
	 * initialize the views, add some listener for it
	 * 
	 * @param root
	 *            the root view
	 */
	public abstract void initComponent(View root);

	/**
	 * update layout of fragment
	 */
	public abstract void update();

	public View getContentView(LayoutInflater inflater) {
		return getContentView(inflater, null, null);
	}

	/**
	 * initialize the content view if the fragment is instance of dialog
	 * fragment then this view will be set to dialog content else it will be
	 * called by onCreateView
	 * 
	 * @param inflater
	 * @return the layout view
	 */
	public View getContentView(LayoutInflater inflater, ViewGroup container,
			Bundle savedInstanceState) {
		View root = inflater.inflate(getContentResource(), container, false);
		if (root == null) {
			throw new RuntimeException("Can't inflate the fragment layout");
		}
		initComponent(root);
		update();
		return root;
	}

	public void setTitle(CharSequence title) {
		if (getActivity() != null)
			getActivity().setTitle(title);
	}

	public void setTitle(int titleId) {
		if (getActivity() != null)
			getActivity().setTitle(titleId);
	}
}
